export const SET_PLAYERS_NAME = "SET_PLAYERS_NAME";
export const RESET_PLAYERS = "RESET_PLAYERS";

export const UPDATE_BOARD = "UPDATE_BOARD";
export const RESET_BOARD = "RESET_BOARD";
export const SET_CURRENT_PLAYER_INDEX = "SET_CURRENT_PLAYER_INDEX";
export const SET_GAME_STATUS = "SET_GAME_STATUS";
export const SET_NUMBER_OF_MOVES = "SET_NUMBER_OF_MOVES";
export const SET_WINNER = "SET_WINNER";
